version: '3'
services:
  cldr-service:
    container_name: cldr-service
    image: jsahleen/cldr-service
    restart: always
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mongo
  cldr-db:
    container_name: cldr-db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"