version: '3'
services:
  cldr-db:
    container_name: cldr-db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  cldr-service:
    container_name: cldr-service
    image: jsahleen/cldr-service
    restart: always
    ports:
      - "${CLDR_PORT}:${CLDR_PORT}"
      - "${CLDR_SSL_PORT}:${CLDR_SSL_PORT}"
    depends_on:
      - cldr-db
    volumes:
      - ./cert:/usr/src/app/cert:ro
    env_file:
      - .env
