version: '3'
services:
  cldr-service:
    container_name: cldr-service
    image: jsahleen/cldr-service
    restart: always
    build: .
    ports:
      - ${CLDR_PORT}:${CLDR_PORT}
    depends_on:
      - mongo
    env_file:
      - .env
  cldr-db:
    container_name: cldr-db
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"